"""
modeling.py
-----------
Leakage-free preprocessing pipeline, model definitions, nested
cross-validation for honest performance estimation, and final model
fitting for deployment.

WHY LEAKAGE MATTERS (read this before the code):
Leakage happens when information from outside the training fold "leaks"
into how the model is built for that fold -- most commonly, when you fit a
transform (imputer, scaler, encoder, resampler) on the WHOLE dataset and
only split into train/test afterward. If you compute e.g. the mean
cholesterol using every patient (including ones in your "test" set), then
impute missing test-set cholesterol values using that mean, the test set
has secretly influenced the model. Performance on that test set is no
longer an honest estimate of how the model will do on a brand-new patient,
because the test set wasn't really "unseen" -- its own statistics helped
build the imputer. The fix used throughout this project: EVERY step that
learns something from data (imputation values, scaling mean/std, one-hot
category list, class-balancing behaviour) lives inside a single
scikit-learn/imblearn Pipeline, and that pipeline is only ever `.fit()` on
a training fold; it is only ever `.transform()`-ed (never re-fit) on the
matching held-out fold. Cross-validation loops fit and evaluate a *fresh*
clone of the pipeline on every fold, so no fold's test data ever touches
that fold's preprocessing.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.metrics import (
    roc_auc_score, confusion_matrix, precision_score, f1_score,
)
from imblearn.pipeline import Pipeline as ImbPipeline
from xgboost import XGBClassifier

from data import (
    CATEGORICAL_FEATURES, BINARY_FEATURES, NUMERIC_FEATURES, ALL_FEATURES,
)

SEED = 42
PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = PROJECT_ROOT / "models"
MODELS_DIR.mkdir(exist_ok=True, parents=True)


def build_preprocessor() -> ColumnTransformer:
    numeric_pipe_scaled = ImbPipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler()),
    ])
    categorical_pipe = ImbPipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ])
    binary_pipe = SimpleImputer(strategy="most_frequent")

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipe_scaled, NUMERIC_FEATURES),
            ("cat", categorical_pipe, CATEGORICAL_FEATURES),
            ("bin", binary_pipe, BINARY_FEATURES),
        ],
        remainder="drop",
    )
    return preprocessor


def build_lr_pipeline() -> ImbPipeline:
    return ImbPipeline([
        ("preprocess", build_preprocessor()),
        ("clf", LogisticRegression(
            class_weight="balanced", max_iter=2000, random_state=SEED
        )),
    ])


def build_xgb_pipeline() -> ImbPipeline:
    return ImbPipeline([
        ("preprocess", build_preprocessor()),
        ("clf", XGBClassifier(
            random_state=SEED, eval_metric="logloss",
        )),
    ])


LR_PARAM_GRID = {"clf__C": [0.01, 0.1, 1, 10]}
XGB_PARAM_GRID = {
    "clf__n_estimators": [100, 200],
    "clf__max_depth": [2, 3, 4],
    "clf__learning_rate": [0.05, 0.1],
}


def nested_cv_oof_predictions(X, y, build_pipeline_fn, param_grid,
                               n_outer=5, n_inner=3, seed=SEED):
    """Returns out-of-fold predicted probabilities for every row in X,
    generated by a model that never saw that row (or its fold-mates)
    during training or hyperparameter tuning."""
    outer_cv = StratifiedKFold(n_splits=n_outer, shuffle=True,
                                random_state=seed)
    oof_proba = np.zeros(len(X))
    fold_best_params = []

    for fold_i, (train_idx, test_idx) in enumerate(outer_cv.split(X, y)):
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        inner_cv = StratifiedKFold(n_splits=n_inner, shuffle=True,
                                    random_state=seed)
        pipe = build_pipeline_fn()
        search = GridSearchCV(pipe, param_grid, scoring="roc_auc",
                               cv=inner_cv, n_jobs=-1)
        search.fit(X_train, y_train)
        fold_best_params.append(search.best_params_)

        proba = search.predict_proba(X_test)[:, 1]
        oof_proba[test_idx] = proba

    return oof_proba, fold_best_params


def bootstrap_auroc_ci(y_true, y_proba, n_boot=2000, seed=SEED):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true)
    y_proba = np.asarray(y_proba)
    n = len(y_true)
    aucs = []
    for _ in range(n_boot):
        idx = rng.integers(0, n, n)
        if len(np.unique(y_true[idx])) < 2:
            continue
        aucs.append(roc_auc_score(y_true[idx], y_proba[idx]))
    lo, hi = np.percentile(aucs, [2.5, 97.5])
    return float(np.mean(aucs)), float(lo), float(hi)


def classification_metrics_at_threshold(y_true, y_proba, threshold=0.5):
    y_pred = (y_proba >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    sensitivity = tp / (tp + fn) if (tp + fn) else np.nan
    specificity = tn / (tn + fp) if (tn + fp) else np.nan
    precision = precision_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    return {
        "threshold": threshold,
        "sensitivity": sensitivity,
        "specificity": specificity,
        "precision": precision,
        "f1": f1,
    }


def calibration_slope_intercept(y_true, y_proba):
    """Fit y_true ~ logit(y_proba) with a 1-feature logistic regression.
    The fitted slope/intercept tell you if the model's probabilities are
    well calibrated: slope ~1 and intercept ~0 means "when the model says
    70% risk, about 70% of those patients really do have disease."""
    eps = 1e-6
    p = np.clip(y_proba, eps, 1 - eps)
    logit_p = np.log(p / (1 - p)).reshape(-1, 1)
    lr = LogisticRegression()
    lr.fit(logit_p, y_true)
    return float(lr.coef_[0][0]), float(lr.intercept_[0])


def fit_final_pipeline(X, y, build_pipeline_fn, param_grid, n_inner=5,
                        seed=SEED):
    """Refit on ALL cleaned data with a fresh hyperparameter search. This
    is the model that ships in the app / notebook demo. It is a DIFFERENT
    object from any single outer-fold model above -- the nested-CV numbers
    estimate how well a model *like this* will generalize; this final fit
    is the actual deployed model, trained with all available data (more
    data = a better final model, but you can no longer honestly evaluate
    it on data it was fit on, which is exactly why the nested-CV numbers
    above are reported as the honest performance estimate, not this
    model's training-set score)."""
    cv = StratifiedKFold(n_splits=n_inner, shuffle=True, random_state=seed)
    pipe = build_pipeline_fn()
    search = GridSearchCV(pipe, param_grid, scoring="roc_auc", cv=cv,
                           n_jobs=-1)
    search.fit(X, y)
    return search.best_estimator_, search.best_params_
